name: 06 - Contexts
on:
    push:
    workflow_dispatch:

jobs:
    echo-data:
        runs-on: ubuntu-latest
        steps: 
            - name: Display Information
              run: |
                echo "Event name: <retrieve the event name here>"
                echo "Ref: <retrieve the ref here>"
                echo "SHA: <retrieve the commit sha here>"
                echo "Actor: <retrieve the actor name here>" 
                echo "Workflow: <retrieve the workflow name here>"
                echo "Run ID: <retrieve the run ID here>"
                echo "Run number: <retrieve the run number here>"
            - name: Retrieve Variable
              run: echo "MY_VAR is ${{ secrets.MY_VAR }}"
