name: 11 - Working with Inputs
on:
    workflow_dispatch:
        inputs:
            dry-run:
                type: boolean
                description: "Skip deployment and only print build output"
                default: false
            target:
                type: environment
                description: "Which environment the workflow will target"
                required: true
            tag:
                type: choice
                description: "Release from which to build and deploy"
                options:
                    - v1
                    - v2
                    - v3
                

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: build
              run: echo "Building from tag ${{ inputs.tag }}"
    deploy:
        runs-on: ubuntu-latest
        needs:
            - build
        if: ${{ inputs.dry-run }}
        environment: ${{ inputs.target }}
        steps:
            - name: deploy
              run: echo "Deploy to ${{ inputs.target }}" 
