name: 12 - Working with Outputs

on:
    workflow_dispatch:
        inputs: 
            build-status:
                type: choice
                options: 
                    - success
                    - failure
                default: success

jobs:
    build:
        runs-on: ubuntu-latest
        outputs:
            build-status-output: ${{ steps.build.outputs.status}}
            output1: ${{ steps.build.outputs.output1 }}


        steps:
            - name: Print GITHUB_OUTPUT path
              run: echo "GITHUB_OUTPUT is $GITHUB_OUTPUT"
            - name: Build
              id: build
              run: |
                echo "status=${{ inputs.build-status }}" >> "$GITHUB_OUTPUT"
                echo "output1='value1'" >> "$GITHUB_OUTPUT"
                echo "output2='value2'" >> "$GITHUB_OUTPUT"
                echo "Github_output: $GITHUB_OUTPUT"
                echo "mistake=true" > "$GITHUB_OUTPUT"
                echo "Github_output again: $GITHUB_OUTPUT"
    deploy:
        runs-on: ubuntu-latest
        needs: build 
        if:  ${{ needs.build.outputs.build-status-output == 'success' }}
        steps:
            - name: Deploy
              run: echo "Deploying"
            - name: Print Outputs
              run: echo ${{ needs.build.outputs.output1 }}