name: 15 - Working with Matrices

on: workflow_dispatch

jobs:
    backwards-compatibility:
        runs-on: ubuntu-latest
        name: ${{ matrix.os }} - ${{ matrix.node-version }}
        strategy:
            fail-fast: true
            matrix:
                node-version: [18.x, 20.x, 21.x]
                os: [ubuntu-latest, windows-latest]
                include:
                    - os: ubuntu-latest
                      node-version: 16.x
                    - os: ubuntu-latest
                      node-version: 21.x
                      tag: experimental
                    
        steps:
            - name: Setup node
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Upload test results
              run: echo "Uloading test results"
            - name: Fail if experimental
              if: ${{ matrix.tag == 'experimental' }}
              run: exit 1

