name: 17-1-custom-actions-composite

run-name: 17- - 1 - Custom Actins - Composite | env - ${{ inputs.target-env }}

env: 
    working-directory: 17-custom-actions/react-app
on:
    workflow_dispatch:
        inputs:
            target-env:
                type: choice
                options:
                    - dev
                    - prod

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ${{ env.working-directory }}
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Setup Node and NPM Dependencies
              uses: ./.github/actions/composite-cache-deps/action.yaml
              with:
                 node-version: 20.x
                 working-dir: ${{ env.working-directory }}
            - name: Test
              run: npm test
            - name: Build
              run: npm run build